spring:
  application:
    name: msb-zuul
  redis:
     database: 0
     host: localhost
     port: 6379
server:
  port: 7002

logging:
  config: classpath:logback.xml
  level:
    com.msb: debug  # spring boot日志级别

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


zuul:
  routes:  #路由规则
    msb-order:  # 应用程序
      path: /order-api/**   # 匹配规则
  ignored-services: "*"   #禁止使用服务名称访问
  sensitive-headers: "company"



# ip请求限制参数  10秒内 连续发送10次，则限制15秒不能再发
blackIp:
  contiueCounts: 10 #ip 连续请求次数
  timeIntervale: 10 #ip 判断的时间间隔
  limitTimes: 15 # 限制的时长 单位为秒



hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 1000000










